config/routes.rb
Rails.application.routes.draw do

  get 'restaraunts/:id', to: 'restaraunts#show'
  get 'restaraunts', to: 'restaraunts#index'
  post 'restaraunts', to: 'restaraunts#create'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact', as: 'feedback'

  get '/', to: 'pages#home'
  #root to: 'pages#home'rails 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
	@categories = %w(pizza starbacks chifan)			
  end
end

app/controllers/restaraunts_controller.rb
class RestarauntsController < ApplicationController

	RESTARAUNTS = [
		{
			name: 'Pizza Hat',
			address: 'Tianfu Square',
			category: 'pizza'
		},
		{
			name: 'Starbucks',
			address: 'Jinsha Museum',
			category: 'coffee'
		},
		{
			name: 'XiaoXiao',
			address: 'Close to my home',
			category: 'hotpot'
		},
	]


	def index
		food_type = nil
		if params['food_type']
			@restaraunts = RESTARAUNTS.select{ |r|
				r[:category] == params['food_type']
			}
		else
			@restaraunts = RESTARAUNTS
		end
		#@restaraunts = Restaraunts.all

	end	

	def create
		#restaraunt = Restaraunts.new(name: params[:name], address: params[:address])
		#restaraunt.save
		render plain: "Add to DB restaurant '#{params[:name]}' "
	end	

	def show
		#Restaraunts.find(params[:id])
		@restaraunt = RESTARAUNTS[params[:id].to_i]
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaraunts_helper.rb
module RestarauntsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheapFood</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<h1>Main header</h1>
    <%= yield %>
    <div>
    	Simple footer
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<p>Find the best restaraunt nearby</p>

<h2>Hello, today is <%= Time.now.strftime('%d/%m/%Y') %> </h2>

<p>
	All our restaraunts <%= link_to 'here', restaraunts_path %>. 
	Give us some <%= link_to 'feedback', feedback_path %>
</p>

<ul>
	<% @categories.each { |category| %>
		<li>
			<%= category %>
		</li>
	<% } %>
</ul>
<p>What do you want to eat?</p>
<form action="/restaraunts" method="get">
	<input type="text" name="food_type" placeholder="What kind of food do you like" >
	<input type="submit">
</form>


<p>Add new restaurant</p>
<form action="/restaraunts" method="post">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	<input type="text" name="name">
	<input type="text" name="address">
	<input type="submit">
</form>

app/views/restaraunts/index.html.erb
<p>Found <%= @restaraunts.count %> available restaraunts</p>

<ul>
	<% @restaraunts.each { |restaraunt| %>
		<li>
			<%= restaraunt[:name] %> (<%= restaraunt[:address] %>) / <%= restaraunt[:category] %>
		</li>
	<% } %>
</ul>

app/views/restaraunts/show.html.erb
<p>More data about <%= @restaraunt[:name] %> </p>